### ISSUE TITLE
duplicate repository

### ISSUE THREAD

**Issue by quozl** [sugarlabs/Simplegraph#3]
this repository is a duplicate of https://github.com/sugarlabs/chart with the latter containing a complete port to Python 3.

**Comment by kshitijdshah99** [comment]
@quozl for me to port this repo to python 3 do I have to refer how porting has been done on this repo[ sugarlabs/chart](https://github.com/sugarlabs/chart)

**Comment by chimosky** [comment]
Seeing as he's saying it's a duplicate, the next steps would be;
- [ ] Note the differences in both activities.
- [ ] Merge some of the differences in one - probably the one already ported to Python3 -
- [ ] Edit the README in this repo to state what's happened, and point people to the other repo.

**Comment by quozl** [comment]
That plan seems reasonable, thanks.

**Comment by kshitijdshah99** [comment]
@chimosky @quozl can you elaborate more on what exactly are you expecting from me to edit the readme of this repo

**Comment by quozl** [comment]
Sorry, not sure which parts of _state what's happened, and point people to the other repo_ you are having trouble with.  Please be clearer?
